#cloud-config

coreos:
  units:
    - name: vmtoolsd.service
      command: start
      content: |
        [Unit]
        Description=VMware Tools Agent
        Documentation=http://open-vm-tools.sourceforge.net/
        ConditionVirtualization=vmware

        [Service]
        ExecStartPre=/usr/bin/ln -sfT /usr/share/oem/vmware-tools /etc/vmware-tools
        ExecStart=/usr/share/oem/bin/vmtoolsd
        TimeoutStopSec=5
    - name: niftycloud-coreos-cloudinit.service
      command: restart
      runtime: yes
      content: |
        [Unit]
        After=coreos-setup-environment.service
        After=vmtoolsd.service
        Requires=coreos-setup-environment.service
        Requires=vmtoolsd.service

        [Service]
        Type=oneshot
        EnvironmentFile=/etc/environment
        ExecStart=/usr/share/oem/bin/niftycloud-coreos-cloudinit
    - name: niftycloud-ssh-key.service
      command: restart
      runtime: yes
      content: |
        [Unit]
        Description=Sets SSH key from vmtoolsd
        [Service]
        Type=oneshot
        StandardOutput=journal+console
        ExecStart=/usr/share/oem/bin/niftycloud-ssh-key
    - name: niftycloud-startup-scripts.service
      command: start
      runtime: yes
      content: |
        [Unit]
        Description=NIFTY Cloud user startup scripts
        After=network.target
        After=local-fs.target
        Requires=network.target
        Requires=local-fs.target
        [Service]
        ExecStart=/usr/share/oem/bin/niftycloud-run-startup-scripts
        Type=idle

        [Install]
        WantedBy=multi-user.target

  oem:
    id: niftycloud
    name: NIFTY Cloud
    version-id: @@OEM_VERSION_ID@@
    home-url: http://cloud.nifty.com/
    bug-report-url: https://github.com/coreos/bugs/issues
